// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgrusqomplyfezrcgrpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncnVzcW9tcGx5ZmV6cmNncnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5MzUyOTYsImV4cCI6MjA4NzUxMTI5Nn0.1E22WqYuL9Nj3Lr0NlogcISlb7eyssgtyLm1MpZ3l40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});